import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArticlePage } from "@/components/ArticlePage";
import { getAllPages, getPage, validateContent } from "@/content";
import { SITE_URL } from "@/lib/urls";

/**
 * Every pSEO page, from one route.
 *
 * `generateStaticParams` turns each content record into a real, separately
 * addressable, statically generated URL at build time. There is no runtime
 * database call, no client-side fetch, and no shell that fills itself in
 * after load: a crawler receives complete HTML for
 * /validation/{slug} exactly as if the page had been written by hand.
 *
 * `dynamicParams = false` means a slug with no record 404s instead of being
 * rendered on demand. That is the honest behaviour for a content site - an
 * unknown URL is a mistake or a stale link, not a page waiting to exist - and
 * it also closes off having thousands of empty URLs generated by anything
 * that guesses at slugs.
 */
export const dynamicParams = false;

export function generateStaticParams() {
  // The ship gate runs here because this is the one function guaranteed to
  // execute during a production build. A malformed record fails the build
  // rather than reaching production, which is the only enforcement that keeps
  // working at page two hundred.
  const problems = validateContent();
  if (problems.length > 0) {
    throw new Error(
      `Content validation failed:\n${problems.map((p) => `  - ${p}`).join("\n")}`,
    );
  }

  return getAllPages().map((page) => ({ slug: page.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const page = getPage(slug);
  if (!page) return {};

  const url = `${SITE_URL}/validation/${page.slug}`;

  return {
    title: page.metaTitle,
    description: page.metaDescription,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      url,
      title: page.metaTitle,
      description: page.metaDescription,
    },
  };
}

export default async function ValidationContentPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const page = getPage(slug);
  if (!page) notFound();

  return <ArticlePage page={page} />;
}
